version: '3.4'

services:
  consultest:
    image: ${DOCKER_REGISTRY}consultest
    build:
      context: .
      dockerfile: ConsulTest/Dockerfile
   noticeservice:
    image: ${DOCKER_REGISTRY}noticeservice
    build:
      context: .
      dockerfile: NoticeService/Dockerfile