version: '3.4'

services:
  consultest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
  noticeservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:8081"